POST http://localhost:3000/tasks
Content-Type: application/json

{
  "title": "Treino de Futebol | Teste",
  "description": "Devo ir para o treino de futebol às 17:00"
}

###

GET http://localhost:3000/tasks

###

PUT http://localhost:3000/tasks/2
Content-Type: application/json

{
  "title": "Treino de Futsal"
}

###

PATCH http://localhost:3000/tasks/1/complete