POST http://localhost:3000/tasks
Content-Type: application/json

{
  "title": "Treino de Futebol",
  "description": "Devo ir para o treino de futebol às 17:00"
}

###

GET http://localhost:3000/tasks

###

GET http://localhost:3000/tasks/suggest-title?description=preciso%20ir%20ao%20cinema%20com%20os%20amigos%20a%20noite

###

PUT http://localhost:3000/tasks/2
Content-Type: application/json

{
  "title": "Treino de Basquete",
  "description": "Treino de Basquete às 11:00"
}

###

PATCH http://localhost:3000/tasks/1/complete

###

PATCH http://localhost:3000/tasks/4/incomplete

###

DELETE http://localhost:3000/tasks/1